name: Run scraper

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '*/30 * * * *'  # Run every 30 minutes

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python src/main.py

      - name: Commit and push changes
        run: |
          git diff
          git config --global user.email "aliceoxenbury@gmail.com"
          git config --global user.name "Ankit"
          git commit -am "Update data" || echo "No changes to commit"
          git push
