name: Run scraper

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '*/30 * * * *'  # Run every 30 minutes

jobs:
  main:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python src/main.py

      - uses: stefanzweifel/git-auto-commit-action@v4
